### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by suzu12** [suzu12/protospace-31669#1]
https://protospace-31669.herokuapp.com/

**Comment by tcamp1234** [comment]
suzu12さん、ご提出ありがとうございます！
お手数おかけいたしますが、Basic認証を実装しているようですので、ユーザー名とパスワードをご教授頂いても宜しいでしょうか？

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by suzu12** [comment]
tcamp1234さん、ご確認していただきありがとうございます。
大変失礼いたしました！Basic認証の記述を一度コメントアウトして、再度デプロイしました！
ユーザー名とパスワードなしで入れるようになっているのも確認いたしました。

お手数おかけいたしますが、ご確認よろしくお願いいたします。

**Comment by tcamp1234** [comment]
suzu12さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by suzu12** [comment]
tcamp1234さん、ご確認をしていただきありがとうございました。

はい。お待ちしております。
今後ともよろしくお願いいたします！
